# Generated by Django 5.2.5 on 2025-09-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
