# Generated by Django 5.2.5 on 2025-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0002_alter_developer_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
